// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTL.TVMaze.Dal.EFCore;

namespace RTL.TVMaze.Dal.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191207133810_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RTL.TVMaze.Generic.Entities.CastCredit", b =>
                {
                    b.Property<int>("CastCreditId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonId");

                    b.Property<int>("ShowId");

                    b.HasKey("CastCreditId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ShowId");

                    b.ToTable("CastCredits");
                });

            modelBuilder.Entity("RTL.TVMaze.Generic.Entities.Person", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<DateTime>("birthday");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("RTL.TVMaze.Generic.Entities.Show", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("RTL.TVMaze.Generic.Entities.CastCredit", b =>
                {
                    b.HasOne("RTL.TVMaze.Generic.Entities.Person", "Person")
                        .WithMany("Characters")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RTL.TVMaze.Generic.Entities.Show")
                        .WithMany("Cast")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
